### ISSUE TITLE
Failure to build with commit c206346

### ISSUE THREAD

**Issue by nowickia** [Fred78290/nct6687d#59] opened 2023-01-22 04:32 UTC
Latest commit [c206346](https://github.com/Fred78290/nct6687d/commit/c2063468a76c67138f5241681b9f24f767600d8d) fails to build - missing enum kinds nct6686d. Added the type to the enum kinds, which compiles, but the new module causes a general protection fault. A couple lines from logs:
kernel: nct6687 nct6687.2592: (null) EC firmware version 1.0 build 09/09/21
kernel: general protection fault, probably for non-canonical address 0x66006c61756e616d: 0000 [#1] PREEMPT SMP NOPTI
kernel: CPU: 4 PID: 3061 Comm: modprobe Tainted: P           OE      6.1.7-arch1-1 #1 a2d6f1dcaa775aaae1f25aaf758ae968e3493665
kernel: Hardware name: Micro-Star International Co., Ltd. MS-7D32/MAG Z690 TOMAHAWK WIFI (MS-7D32), BIOS H.90 11/10/2022

Commit [c38e309](https://github.com/Fred78290/nct6687d/commit/c38e309bd281ac26258e90a983d9c71723d34fcc) works without issue.

**Comment by Fred78290** [comment] 2023-01-22 10:29
Thank you for report.

The problem is now fixed with the PR #60

**Closed by Fred78290** 2023-01-22 10:29 UTC
